/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Games: () => import('#controllers/games_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  QuestionSets: () => import('#controllers/question_sets_controller'),
  Questions: () => import('#controllers/questions_controller'),
  Session: () => import('#controllers/session_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
}
