/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GameSessionSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'endTime',
    'hostId',
    'id',
    'name',
    'questionIds',
    'questionSetId',
    'startTime',
    'status',
    'timeLimitMinutes',
    'updatedAt',
  ] as const
  $columns = GameSessionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare endTime: DateTime | null
  @column()
  declare hostId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare questionIds: any | null
  @column()
  declare questionSetId: number | null
  @column.dateTime()
  declare startTime: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare timeLimitMinutes: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuestionSetQuestionSchema extends BaseModel {
  static $columns = ['questionId', 'questionSetId'] as const
  $columns = QuestionSetQuestionSchema.$columns
  @column()
  declare questionId: number | null
  @column({ isPrimary: true })
  declare questionSetId: number | null
}

export class QuestionSetSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = QuestionSetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuestionSchema extends BaseModel {
  static $columns = [
    'correctAnswerIndex',
    'createdAt',
    'id',
    'imageData',
    'options',
    'questionText',
    'updatedAt',
  ] as const
  $columns = QuestionSchema.$columns
  @column()
  declare correctAnswerIndex: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageData: string | null
  @column()
  declare options: any
  @column()
  declare questionText: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SessionPlayerSchema extends BaseModel {
  static $columns = [
    'activeGameState',
    'avatarConfig',
    'createdAt',
    'id',
    'sessionId',
    'sessionScore',
    'updatedAt',
    'userId',
  ] as const
  $columns = SessionPlayerSchema.$columns
  @column()
  declare activeGameState: any | null
  @column()
  declare avatarConfig: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sessionId: number | null
  @column()
  declare sessionScore: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'activeGameState',
    'answeredQuestions',
    'botDifficulty',
    'createdAt',
    'currentStreak',
    'email',
    'id',
    'isAdmin',
    'providerId',
    'score',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare activeGameState: any | null
  @column()
  declare answeredQuestions: any | null
  @column()
  declare botDifficulty: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentStreak: number | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean | null
  @column()
  declare providerId: string | null
  @column()
  declare score: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
